export const countries = [
  {"country-code": "ad", "country": "Andorra"},
  {"country-code": "ae", "country": "United Arab Emirates"},
  {"country-code": "af", "country": "Afghanistan"},
  {"country-code": "ag", "country": "Antigua and Barbuda"},
  {"country-code": "ai", "country": "Anguilla"},
  {"country-code": "al", "country": "Albania"},
  {"country-code": "am", "country": "Armenia"},
  {"country-code": "ao", "country": "Angola"},
  {"country-code": "ar", "country": "Argentina"},
  {"country-code": "at", "country": "Austria"},
  {"country-code": "au", "country": "Australia"},
  {"country-code": "aw", "country": "Aruba"},
  {"country-code": "ax", "country": "Åland Islands"},
  {"country-code": "az", "country": "Azerbaijan"},
  {"country-code": "ba", "country": "Bosnia and Herzegovina"},
  {"country-code": "bb", "country": "Barbados"},
  {"country-code": "bd", "country": "Bangladesh"},
  {"country-code": "be", "country": "Belgium"},
  {"country-code": "bf", "country": "Burkina Faso"},
  {"country-code": "bg", "country": "Bulgaria"},
  {"country-code": "bh", "country": "Bahrain"},
  {"country-code": "bi", "country": "Burundi"},
  {"country-code": "bj", "country": "Benin"},
  {"country-code": "bm", "country": "Bermuda"},
  {"country-code": "bn", "country": "Brunei"},
  {"country-code": "bo", "country": "Bolivia"},
  {"country-code": "br", "country": "Brazil"},
  {"country-code": "bs", "country": "Bahamas"},
  {"country-code": "bt", "country": "Bhutan"},
  {"country-code": "bw", "country": "Botswana"},
  {"country-code": "by", "country": "Belarus"},
  {"country-code": "bz", "country": "Belize"},
  {"country-code": "ca", "country": "Canada"},
  {"country-code": "cd", "country": "Congo (Democratic Republic)"},
  {"country-code": "cf", "country": "Central African Republic"},
  {"country-code": "cg", "country": "Congo"},
  {"country-code": "ch", "country": "Switzerland"},
  {"country-code": "ci", "country": "Côte d'Ivoire"},
  {"country-code": "cl", "country": "Chile"},
  {"country-code": "cm", "country": "Cameroon"},
  {"country-code": "cn", "country": "China"},
  {"country-code": "co", "country": "Colombia"},
  {"country-code": "cr", "country": "Costa Rica"},
  {"country-code": "cu", "country": "Cuba"},
  {"country-code": "cv", "country": "Cabo Verde"},
  {"country-code": "cy", "country": "Cyprus"},
  {"country-code": "cz", "country": "Czechia"},
  {"country-code": "de", "country": "Germany"},
  {"country-code": "dj", "country": "Djibouti"},
  {"country-code": "dk", "country": "Denmark"},
  {"country-code": "dm", "country": "Dominica"},
  {"country-code": "do", "country": "Dominican Republic"},
  {"country-code": "dz", "country": "Algeria"},
  {"country-code": "ec", "country": "Ecuador"},
  {"country-code": "ee", "country": "Estonia"},
  {"country-code": "eg", "country": "Egypt"},
  {"country-code": "es", "country": "Spain"},
  {"country-code": "et", "country": "Ethiopia"},
  {"country-code": "fi", "country": "Finland"},
  {"country-code": "fj", "country": "Fiji"},
  {"country-code": "fr", "country": "France"},
  {"country-code": "ga", "country": "Gabon"},
  {"country-code": "gb", "country": "United Kingdom"},
  {"country-code": "gd", "country": "Grenada"},
  {"country-code": "ge", "country": "Georgia"},
  {"country-code": "gh", "country": "Ghana"},
  {"country-code": "gm", "country": "Gambia"},
  {"country-code": "gn", "country": "Guinea"},
  {"country-code": "gq", "country": "Equatorial Guinea"},
  {"country-code": "gr", "country": "Greece"},
  {"country-code": "gt", "country": "Guatemala"},
  {"country-code": "gw", "country": "Guinea-Bissau"},
  {"country-code": "gy", "country": "Guyana"},
  {"country-code": "hn", "country": "Honduras"},
  {"country-code": "hr", "country": "Croatia"},
  {"country-code": "ht", "country": "Haiti"},
  {"country-code": "hu", "country": "Hungary"},
  {"country-code": "id", "country": "Indonesia"},
  {"country-code": "ie", "country": "Ireland"},
  {"country-code": "il", "country": "Israel"},
  {"country-code": "in", "country": "India"},
  {"country-code": "iq", "country": "Iraq"},
  {"country-code": "ir", "country": "Iran"},
  {"country-code": "is", "country": "Iceland"},
  {"country-code": "it", "country": "Italy"},
  {"country-code": "jm", "country": "Jamaica"},
  {"country-code": "jo", "country": "Jordan"},
  {"country-code": "jp", "country": "Japan"},
  {"country-code": "ke", "country": "Kenya"},
  {"country-code": "kg", "country": "Kyrgyzstan"},
  {"country-code": "kh", "country": "Cambodia"},
  {"country-code": "ki", "country": "Kiribati"},
  {"country-code": "km", "country": "Comoros"},
  {"country-code": "kn", "country": "Saint Kitts and Nevis"},
  {"country-code": "kp", "country": "North Korea"},
  {"country-code": "kr", "country": "South Korea"},
  {"country-code": "kw", "country": "Kuwait"},
  {"country-code": "ky", "country": "Cayman Islands"},
  {"country-code": "kz", "country": "Kazakhstan"},
  {"country-code": "la", "country": "Laos"},
  {"country-code": "lb", "country": "Lebanon"},
  {"country-code": "lc", "country": "Saint Lucia"},
  {"country-code": "li", "country": "Liechtenstein"},
  {"country-code": "lk", "country": "Sri Lanka"},
  {"country-code": "lr", "country": "Liberia"},
  {"country-code": "ls", "country": "Lesotho"},
  {"country-code": "lt", "country": "Lithuania"},
  {"country-code": "lu", "country": "Luxembourg"},
  {"country-code": "lv", "country": "Latvia"},
  {"country-code": "ly", "country": "Libya"},
  {"country-code": "ma", "country": "Morocco"},
  {"country-code": "mc", "country": "Monaco"},
  {"country-code": "md", "country": "Moldova"},
  {"country-code": "me", "country": "Montenegro"},
  {"country-code": "mg", "country": "Madagascar"},
  {"country-code": "mh", "country": "Marshall Islands"},
  {"country-code": "mk", "country": "North Macedonia"},
  {"country-code": "ml", "country": "Mali"},
  {"country-code": "mm", "country": "Myanmar"},
  {"country-code": "mn", "country": "Mongolia"},
  {"country-code": "mo", "country": "Macao"},
  {"country-code": "mr", "country": "Mauritania"},
  {"country-code": "mt", "country": "Malta"},
  {"country-code": "mu", "country": "Mauritius"},
  {"country-code": "mv", "country": "Maldives"},
  {"country-code": "mw", "country": "Malawi"},
  {"country-code": "mx", "country": "Mexico"},
  {"country-code": "my", "country": "Malaysia"},
  {"country-code": "mz", "country": "Mozambique"},
  {"country-code": "na", "country": "Namibia"},
  {"country-code": "ne", "country": "Niger"},
  {"country-code": "ng", "country": "Nigeria"},
  {"country-code": "ni", "country": "Nicaragua"},
  {"country-code": "nl", "country": "Netherlands"},
  {"country-code": "no", "country": "Norway"},
  {"country-code": "np", "country": "Nepal"},
  {"country-code": "nr", "country": "Nauru"},
  {"country-code": "nz", "country": "New Zealand"},
  {"country-code": "om", "country": "Oman"},
  {"country-code": "pa", "country": "Panama"},
  {"country-code": "pe", "country": "Peru"},
  {"country-code": "pg", "country": "Papua New Guinea"},
  {"country-code": "ph", "country": "Philippines"},
  {"country-code": "pk", "country": "Pakistan"},
  {"country-code": "pl", "country": "Poland"},
  {"country-code": "pt", "country": "Portugal"},
  {"country-code": "py", "country": "Paraguay"},
  {"country-code": "qa", "country": "Qatar"},
  {"country-code": "ro", "country": "Romania"},
  {"country-code": "rs", "country": "Serbia"},
  {"country-code": "ru", "country": "Russia"},
  {"country-code": "rw", "country": "Rwanda"},
  {"country-code": "sa", "country": "Saudi Arabia"},
  {"country-code": "sb", "country": "Solomon Islands"},
  {"country-code": "sc", "country": "Seychelles"},
  {"country-code": "sd", "country": "Sudan"},
  {"country-code": "se", "country": "Sweden"},
  {"country-code": "sg", "country": "Singapore"},
  {"country-code": "si", "country": "Slovenia"},
  {"country-code": "sk", "country": "Slovakia"},
  {"country-code": "sl", "country": "Sierra Leone"},
  {"country-code": "sm", "country": "San Marino"},
  {"country-code": "sn", "country": "Senegal"},
  {"country-code": "so", "country": "Somalia"},
  {"country-code": "sr", "country": "Suriname"},
  {"country-code": "ss", "country": "South Sudan"},
  {"country-code": "st", "country": "Sao Tome and Principe"},
  {"country-code": "sv", "country": "El Salvador"},
  {"country-code": "sz", "country": "Eswatini"},
  {"country-code": "td", "country": "Chad"},
  {"country-code": "tg", "country": "Togo"},
  {"country-code": "th", "country": "Thailand"},
  {"country-code": "tj", "country": "Tajikistan"},
  {"country-code": "tl", "country": "Timor-Leste"},
  {"country-code": "tm", "country": "Turkmenistan"},
  {"country-code": "tn", "country": "Tunisia"},
  {"country-code": "to", "country": "Tonga"},
  {"country-code": "tr", "country": "Turkey"},
  {"country-code": "tt", "country": "Trinidad and Tobago"},
  {"country-code": "tv", "country": "Tuvalu"},
  {"country-code": "tz", "country": "Tanzania"},
  {"country-code": "ua", "country": "Ukraine"},
  {"country-code": "ug", "country": "Uganda"},
  {"country-code": "us", "country": "United States"},
  {"country-code": "uy", "country": "Uruguay"},
  {"country-code": "uz", "country": "Uzbekistan"},
  {"country-code": "va", "country": "Vatican City"},
  {"country-code": "vc", "country": "Saint Vincent and the Grenadines"},
  {"country-code": "ve", "country": "Venezuela"},
  {"country-code": "vg", "country": "British Virgin Islands"},
  {"country-code": "vi", "country": "U.S. Virgin Islands"},
  {"country-code": "vn", "country": "Vietnam"},
  {"country-code": "vu", "country": "Vanuatu"},
  {"country-code": "ws", "country": "Samoa"},
  {"country-code": "ye", "country": "Yemen"},
  {"country-code": "za", "country": "South Africa"},
  {"country-code": "zm", "country": "Zambia"},
  {"country-code": "zw", "country": "Zimbabwe"}
]


export const languages = [
  {"language-code": "aa", "language": "Afar"},
  {"language-code": "am", "language": "Amharic"},
  {"language-code": "ar", "language": "Arabic"},
  {"language-code": "bn", "language": "Bengali"},
  {"language-code": "bs", "language": "Bosnian"},
  {"language-code": "bg", "language": "Bulgarian"},
  {"language-code": "my", "language": "Burmese"},
  {"language-code": "zh", "language": "Chinese"},
  {"language-code": "hr", "language": "Croatian"},
  {"language-code": "cs", "language": "Czech"},
  {"language-code": "da", "language": "Danish"},
  {"language-code": "nl", "language": "Dutch"},
  {"language-code": "en", "language": "English"},
  {"language-code": "et", "language": "Estonian"},
  {"language-code": "fi", "language": "Finnish"},
  {"language-code": "fr", "language": "French"},
  {"language-code": "de", "language": "German"},
  {"language-code": "el", "language": "Greek"},
  {"language-code": "he", "language": "Hebrew"},
  {"language-code": "hi", "language": "Hindi"},
  {"language-code": "hu", "language": "Hungarian"},
  {"language-code": "is", "language": "Icelandic"},
  {"language-code": "id", "language": "Indonesian"},
  {"language-code": "it", "language": "Italian"},
  {"language-code": "ja", "language": "Japanese"},
  {"language-code": "ko", "language": "Korean"},
  {"language-code": "lo", "language": "Lao"},
  {"language-code": "lv", "language": "Latvian"},
  {"language-code": "lt", "language": "Lithuanian"},
  {"language-code": "mk", "language": "Macedonian"},
  {"language-code": "ms", "language": "Malay"},
  {"language-code": "mt", "language": "Maltese"},
  {"language-code": "mr", "language": "Marathi"},
  {"language-code": "mi", "language": "Māori"},
  {"language-code": "ne", "language": "Nepali"},
  {"language-code": "nb", "language": "Norwegian"},
  {"language-code": "no", "language": "Norwegian"},
  {"language-code": "fa", "language": "Persian"},
  {"language-code": "pl", "language": "Polish"},
  {"language-code": "pt", "language": "Portuguese"},
  {"language-code": "ro", "language": "Romanian"},
  {"language-code": "ru", "language": "Russian"},
  {"language-code": "sr", "language": "Serbian"},
  {"language-code": "si", "language": "Sinhalese"},
  {"language-code": "sk", "language": "Slovak"},
  {"language-code": "sl", "language": "Slovene"},
  {"language-code": "so", "language": "Somali"},
  {"language-code": "es", "language": "Spanish"},
  {"language-code": "sv", "language": "Swedish"},
  {"language-code": "tg", "language": "Tajik"},
  {"language-code": "ta", "language": "Tamil"},
  {"language-code": "te", "language": "Telugu"},
  {"language-code": "th", "language": "Thai"},
  {"language-code": "tr", "language": "Turkish"},
  {"language-code": "uk", "language": "Ukrainian"},
  {"language-code": "ur", "language": "Urdu"},
  {"language-code": "uz", "language": "Uzbek"},
  {"language-code": "vi", "language": "Vietnamese"}
]



export const categories = [
  "politics",
  "sports",
  "business",
  "technology",
  "entertainment",
  "health",
  "science",
  "lifestyle",
  "travel",
  "culture",
  "education",
  "environment",
  "other"
]